Text and link fixes
platanus/fintual-edu pull request #32
Opened 2020-05-04 23:52 UTC by danieldt

Just minor texts and link updates.

**DO NOT MERGE YET**

2020-05-05 00:24 UTC, francescafinaldi requested changes

2020-05-05 00:24 UTC, francescafinaldi commented on content/post/ganarle-al-mercado-1.md
> +La primera compañía pública listada en la bolsa en la historia tendría hoy una capitalización bursátil de aproximadamente US$ 7,9 billones, unas 270 veces el PIB de Chile. Se trata de la Compañía Nee
en bolsa está bien :)

2020-05-05 00:27 UTC, danieldt commented on content/post/ganarle-al-mercado-1.md
> +La primera compañía pública listada en la bolsa en la historia tendría hoy una capitalización bursátil de aproximadamente US$ 7,9 billones, unas 270 veces el PIB de Chile. Se trata de la Compañía Nee
Oka, le saco el "la" no más?

2020-05-05 01:15 UTC, francescafinaldi commented on content/post/ganarle-al-mercado-1.md
> +La primera compañía pública listada en la bolsa en la historia tendría hoy una capitalización bursátil de aproximadamente US$ 7,9 billones, unas 270 veces el PIB de Chile. Se trata de la Compañía Nee
sí! gracias :D

2020-05-06 16:10 UTC, francescafinaldi approved these changes
súper! gracias

2020-05-07 23:40 UTC, merged